### ISSUE TITLE
Unable to create sample Setting via Swagger UI

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm-rest-api#164]
**Describe the bug**
It is not possible to create sample Seting via Settings#POST method

**To Reproduce**
1. Authenticate to swagger-ui as administrator
2. Execute Settings#POST

**Expected behavior**
Request passes successfully

**Observed behavior**
Error is returned

**Screenshots**
![obraz](https://user-images.githubusercontent.com/47355402/67602269-8de04e80-f776-11e9-91c9-be491ed98a6d.png)

**Additional context**
N/A

**Comment by Crystalzord** [comment]
Implementing a POST endpoint requires a major refactoring of the implementation on the oscm repository. Currently it worked the same way as PUT endpoint - it allowed only to update the existing predefined settings. I am closing the issue since this is not really a bug of Swagger UI. Refactoring of the implementation on oscm repository should be planned first.
See classes: 
 - ConfigurationKey from interfaces
 - OperatorServiceBean#869 from oscm
